spring.application.name: member-service

jwt:
  secret: fanshop-member-service-jwt-secret-key-must-be-at-least-256bits
  expiration-ms: 86400000  # 24시간
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
      - db-core.yml
      - client-example.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update

storage:
  database:
    core-db:
      url: localhost:3306/member_db?serverTimezone=UTC&characterEncoding=UTF-8
      username: fanshop
      password: fanshop

---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live

