spring.application.name: order-service
spring.profiles.active: local

jwt:
  secret: fanshop-member-service-jwt-secret-key-must-be-at-least-256bits
  expiration-ms: 86400000

product-service:
  url: http://localhost:8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fanshop.kafka.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:orderdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring.config.activate.on-profile: local-dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fanshop
    password: fanshop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
