spring.application.name: product-service
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
      - db-core.yml
  web.resources.add-mappings: false
  cloud:
    function:
      definition: orderCreatedConsumer
    stream:
      default:
        contentType: application/json
      bindings:
        orderCreatedConsumer-in-0:
          destination: order.created
          group: product-service
        stockResult-out-0:
          destination: stock.result
      kafka:
        binder:
          brokers: localhost:9092

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local

server:
  port: 8081

---
spring.config.activate.on-profile: local-dev

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fanshop
    password: fanshop
  jpa:
    hibernate:
      ddl-auto: update

---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
