management:
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    resource:
      attributes:
        service.name: ${spring.application.name:unknown-service}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo:
        http:
          server:
            requests: 10, 50, 100, 200, 500, 1000, 2000

spring:
  threads:
    virtual:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          enable-observation: true
